exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

# Site settings
title: "법률사무소 다물"
subtitle: "법률사무소 다물"
description: "신뢰할 수 있는 법률 사무소, 다물"
keywords: "법률사무소, 변호사, 다물, damurchambers"
url: "https://damurchambers.github.io" # the base hostname & protocol for your site
# baseurl: "/" # Set this value to "" if you want your site to be root
baseurl: ""
cover: ""
logo: "/assets/logo.png"

# Build settings
markdown: kramdown

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."
